---
# Node and NPM
- name: Add Node Repository
  get_url:
    url: https://rpm.nodesource.com/setup_lts.x
    dest: /tmp/setup_lts.x
  notify:
    - Run Node setup Script

- name: Run Node setup Script
  become: true
  shell:
    cmd: bash /tmp/setup_lts.x

# Docker
- name: Add docker-ce repo
  become: true
  get_url:
    url: "{{ docker_repo }}"
    dest: /etc/yum.repos.d/

# - name: Add Docker Repo
#   become: true
#   get_url:
#     url: "{{docker_repo}}"
#     dest: /etc/yum.repos.d/
#   tags: "docker"

# AWX
- name: Cloning AWX Repo
  become: true
  git:
    clone: true
    force: true
    repo: "{{ awx_repo }}"
    version: "{{ awx_branch }}"
    dest: /tmp/awx/
  tags: "awx"
