---

# Make Installation
- name: Ensure GNU Make are installed
  become: true
  yum:
    update_cache: yes
    state: present
    name: "@Development tools"

# Node Installation
- name: Install and Configure Node / NPM
  block:

    - name: Install NodeJs and NPM
      yum:
        update_cache: yes
        state: latest
        name: nodejs
      tags: "node"
  become: true

# Docker Installation
- name: Install and Configure Docker
  block:
    - name: Install Docker Pre-Req
      yum:
        update_cache: yes
        state: latest
        name: "{{ docker_req }}"
      tags: "docker"

    - name: Install Docker Engine
      yum:
        update_cache: yes
        state: latest
        name: "{{ docker_pkgs }}"
      tags: "docker"

    - name: Start Docker
      service:
        name: docker
        state: restarted
        enabled: yes
      tags: "docker"

    - name: Check if docker.sock exists
      stat:
        path: /var/run/docker.sock
      register: docker_daemon
      tags: "docker"

    - name: Change docker.sock ownership
      file:
        path: /var/run/docker.sock
        owner: "{{ host_user }}"
      when: docker_daemon.stat.exists
      tags: "docker"
  become: true

