---

- name: Ensure GNU Make are installed
  become: true
  yum:
    state: present
    name: "@Development tools"
    update_cache: yes

# Node Installation
- name: Add Node Repository
  become: true
  get_url: 
    url: https://rpm.nodesource.com/setup_lts.x
    dest: /tmp/setup_lts.x
  notify:
    - Run Node setup Script
  tags: "node"

- name: Install NodeJs and NPM
  become: true
  yum:
    state: latest
    name: nodejs
  tags: "node"

# Docker Installation
- name: Install Docker Pre-Req
  become: true
  yum:
    state: latest
    name: "{{ req_pkgs }}"

- name: Add Docker Repository
  become: true
  get_url: 
    url: "{{ docker_repo }}"
    dest: /etc/yum.repos.d/
  tags: "docker"

- name: Install Docker Engine
  become: true
  yum:
    state: latest
    name: "{{ docker_pkgs }}"
  tags: "docker"

