---
# Make
- name: Ensure GNU Make are installed
  become: true
  yum:
    update_cache: true
    state: present
    name: "@Development tools"

# NodeJS
- name: Install NodeJs and NPM
  become: true
  yum:
    update_cache: true
    state: latest
    name: nodejs

# Docker
- name: Docker and Docker Compose installation and configuration
  become: true
  block:
    - name: Removing older versions
      yum:
        name: "{{ docker_older_pkgs }}"
        state: absent

    - name: Installing Docker Engine
      yum:
        name: "{{ docker_pkgs }}"

    - name: Starting docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Adding user to group Docker
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: true

    - name: Installing docker-compose python module
      pip:
        name: docker-compose

    - name: Installing Docker-Compose
      become: true
      get_url:
        url: "{{ docker_compose_repo }}"
        dest: "{{ docker_compose_path }}"
        mode: 755

    # - name: Install Docker Pre-Req
    #   yum:
    #     update_cache: true
    #     state: latest
    #     name: "{{ docker_req }}"

    # - name: Install Docker Engine
    #   yum:
    #     update_cache: true
    #     state: latest
    #     name: "{{ docker_pkgs }}"

    # - name: Start Docker
    #   service:
    #     name: docker
    #     state: restarted
    #     enabled: true

    # - name: Adding user to docker group
    #   command: usermod -a -G docker $USER

    # - name: Adding priveleges to docker.sock
    #   command : chown $USER /var/run/docker.sock
