---

# Make Installation
- name: Ensure GNU Make are installed
  become: true
  yum:
    update_cache: yes
    state: present
    name: "@Development tools"

# Node Installation
- name: Install and Configure Node / NPM
  block:

    - name: Install NodeJs and NPM
      yum:
        update_cache: yes
        state: latest
        name: nodejs
      tags: "node"
  become: true

# Docker Installation
- name: Install and Configure Docker
  block:
    - name: Install Docker Pre-Req
      yum:
        update_cache: yes
        state: latest
        name: "{{ docker_req }}"

    - name: Install Docker Engine
      yum:
        update_cache: yes
        state: latest
        name: "{{ docker_pkgs }}"

    - name: Start Docker
      service:
        name: docker
        state: restarted
        enabled: yes

    - name: Check if docker.sock exists
      stat:
        path: /var/run/docker.sock
      register: docker_daemon

    - name: Change docker.sock ownership
      file:
        path: /var/run/docker.sock
        owner: "{{ host_user }}"
      # loop:
      #   - { file_path: /var/run/docker.sock, user_owner: "{{ host_user }}" }
      #   - { file_path: /var/run/docker.pid, user_owner: "{{ host_user }}" }
      #   - { file_path: /var/run/docker/, user_owner: "{{ host_user }}" }
      when: docker_daemon.stat.exists

    - name: Change docker.pid ownership
      file:
        state: directory
        owner: "{{ host_user }}"
        path: /var/run/docker.pid

    - name: Change docker ownership
      file:
        state: directory
        owner: "{{ host_user }}"
        path: /var/run/docker/
  become: true
  tags: "docker"

