---

- name: Install Ansible
  become: true
  yum:
    name: ansible
    state: latest

- name: Check if AWX Repo exists
  stat:
    path: /tmp/awx/
  register: awx_repo
  tags: "awx"

- name: Install and Configure AWX
  block:
    - name: Change user parameters in AWX inventory
      replace:
        path: /tmp/awx/installer/inventory
        backup: yes
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      loop:
        - { regex: 'admin_user=admin', value: 'admin_user={{ host_user }}' }
        - { regex: '# admin_password=password', value: 'admin_password={{ host_pass }}'}

    - name: Install AWX
      shell: ansible-playbook -i inventory install.yml
      args:
        chdir: /tmp/awx/installer/
  become: true
  when: awx_repo.stat.exists
  tags: "awx"

