---

- name: Update Repo
  become: true
  yum:
    state: latest
    name: "*"
    exclude: kernel*
  tags: "update"

- name: Add EPEL Repo
  become: true
  yum:
    state: latest
    name: epel-release
    update_cache: yes

- name: Install Common Apps
  become: true
  yum:
    state: latest
    name: "{{ common_pkgs }}"
